# Pre-commit hooks for enforcing Pythonic code standards
# Run: pre-commit install
# Manual: pre-commit run --all-files

repos:
  # Ruff - Fast Python linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.0
    hooks:
      - id: ruff
        name: ruff-lint
        args: [--fix, --exit-non-zero-on-fix]
        types_or: [python, pyi, jupyter]
      - id: ruff-format
        name: ruff-format
        types_or: [python, pyi, jupyter]

  # Type checking with mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
      - id: mypy
        name: mypy
        args: [--strict, --ignore-missing-imports, --explicit-package-bases]
        additional_dependencies: [
          pydantic>=2.5.0,  # Has built-in types but needed in isolated env
          types-requests>=2.31.0,  # Type stubs for requests
        ]
        types: [python]
        exclude: ^tests/

  # Security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        name: bandit-security
        args: [-r, --skip, B101]
        exclude: ^tests/

  # YAML/TOML/JSON formatting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        args: [--unsafe]
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: detect-private-key
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: debug-statements  # Catch print() and breakpoint() calls
      - id: check-added-large-files  # Prevent committing large files
        args: ['--maxkb=5000']  # 5MB max file size

  # Python specific checks
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-no-log-warn
      - id: python-use-type-annotations

  # Docstring checks (disabled initially - too many existing violations)
  # Enable this after cleaning up existing code
  # - repo: https://github.com/PyCQA/pydocstyle
  #   rev: 6.3.0
  #   hooks:
  #     - id: pydocstyle
  #       args: [--convention=google, --add-ignore=D100,D101,D102,D103,D104,D107]
  #       additional_dependencies: [tomli]
  #       exclude: ^tests/

  # Markdown formatting (only if you have lots of markdown docs)
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.19
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat-black
        exclude: ^CLAUDE.md$

default_language_version:
  python: python3.11

# Ensure hooks run in CI with same Python version
ci:
  autofix_prs: true
  autoupdate_schedule: monthly
  skip: []
